[build]
  base = "frontend"
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://smart-pdf-backend.onrender.com"
  NEXT_PUBLIC_WIDGET_URL = "https://pdf.djaouad.tech/widget.js"
