services:
  - type: web
    name: smart-pdf-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm ci && npm run build
    startCommand: node dist/main
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: google/gemini-2.5-flash
      - key: OPENAI_API_KEY
        sync: false
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: APP_URL
        value: https://smart-pdf-backend-vyh7.onrender.com
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: MAIL_FROM_NAME
        value: Smart PDF Workspace
      - key: MAIL_FROM_EMAIL
        value: no-reply@djaouad.tech
      - key: FRONTEND_URL
        value: https://docs.djaouad.tech
